# TODO use .env file for environment variables
version: "3.8"

services:
  user_service_db:
    container_name: user_service_db
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dev_db
    ports:
      - "9910:5432"
    volumes:
      - user_service_db:/var/lib/postgresql/data
    restart: always

  user_service_test_db:
    container_name: user_service_test_db
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test_db
    ports:
      - "8910:5432"
    volumes:
      - user_service_test_db:/var/lib/postgresql/data
    restart: always


volumes:
  user_service_db: {}
  user_service_test_db: {}

