[profile.default]
src = "src"
out = "out"
libs = ["lib"]
[dependencies]
openzeppelin-contracts = { version = "5.0.2", git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git" }

[profile.release]
optimize = true
optimizer_runs = 200

[etherscan]


[rpc_endpoints]
holesky = "https://rpc.ankr.com/eth_holesky"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
